### ISSUE TITLE
Add expression name to the template tests

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/autotest#13]
When there are lots of objects being tested in one autotest block, if you get a message like this:
```python
type is not "str"
```
it's hard to know *which* object is being tested. Instead we want to output something like
```python
type of foo() is not "str"
```
which tells the student what object has the wrong type.

We could include this in the test template. For example, instead of

```python
str:
        - test: "len({{snippet}})"
          fail: "length is not correct"
```
we could do
```python
str:
        - test: "len({{snippet}})"
          fail: "length of {{snippet}} is not correct"
```
and then add code to instantiate the template not just on the test but on the fail message too.

**Comment by Alireza-Iranpour** [comment]
Addressed in
https://github.com/UBC-DSCI/autotest/commit/8d65995541cfccdd062cc76e30d688b60c2e6d3e
