### ISSUE TITLE
enable the limittestcellheight extension in the docker image

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/autotest#15]
Currently the extension to limit test cell heights is not enabled in the docker image.

**Comment by Alireza-Iranpour** [comment]
Cause: The `nbgrader` extensions were being installed before running the `install_autotest.sh` which added the limit_cell_height extension to `nbgrader`

Fix: added the `nbgrader` extensions installation steps to the end of the `install_autotest.sh` file
