### ISSUE TITLE
Adding a 'generate_autotest' app to create the instantiated solution notebooks

### ISSUE THREAD

**Issue by Alireza-Iranpour** [UBC-DSCI/autotest#19]
This allows instructors to create an instantiated notebook which also contains the solutions for easier evaluation of the generated tests

Example: nbgrader generate_autotest --force ps3

**Comment by trevorcampbell** [comment]
Duplicate of #8

**Comment by Alireza-Iranpour** [comment]
Resolved in 
https://github.com/UBC-DSCI/autotest/commit/c9d83dc93e4b65988b9cb0c0b5185e4246a79f92
