### ISSUE TITLE
Debugging test code

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/autotest#8]
Given that the instantiated tests only appear in the release version, it might be hard for instructors to check / debug the test code that gets generated. 

Perhaps we could add a converter `nbgrader instantiate_tests` that just takes the `source/` version and outputs to an `instantiated/` version that contains both the full solutions as well as instantiated test code.

We could largely copy the `generate_assignment` converter, but just get rid of steps that remove solutions and make the notebook read-only.

**Comment by Alireza-Iranpour** [comment]
Resolved in
https://github.com/UBC-DSCI/autotest/commit/f40115b7a3f8091161ffbf2c40be1f010357c2db
